 const artists = [
    "(Hed) P.E.",
    "3 Doors Down",
    "369",
    "3LAU",
    "A Static Lullaby",
    "A Teardrop In The Lake",
    "AC/DC",
    "AFI",
    "AFTRHOURS",
    "AMBIE",
    "AURORA",
    "Aaron Smith",
    "Above & Beyond",
    "Adele",
    "Agnes Obel",
    "Airwaves",
    "Alaina Castillo",
    "Alaskan Tapes",
    "Alberto L. Ferro",
    "Alesso",
    "Alexander Motovilov",
    "Alexander Wren",
    "Alexi Musnitsky",
    "Alice Boman",
    "Alice In Chains",
    "Alien Ant Farm",
    "Alok",
    "Alphabeat",
    "Alvvays",
    "Amaranth Cove",
    "Amoll",
    "Amy Winehouse",
    "Anberlin",
    "Andre Ehmann",
    "Andrew Gold",
    "Angel Olsen",
    "Anna Calvi",
    "Annelie",
    "Ansatz Der Maschine",
    "Anson Seabra",
    "Anthony Ramos",
    "Antonio Giacca",
    "Antuigo",
    "Apparat",
    "Aquilo",
    "Arlo Day",
    "Arlo Parks",
    "Armin van Buuren",
    "Armor For Sleep",
    "Arthur Jussen",
    "Arya Shae",
    "Atlas Sound",
    "Audien",
    "Autoerotique",
    "Avenged Sevenfold",
    "Avery Young",
    "Avicii",
    "BADBADNOTGOOD",
    "BANKS",
    "Barry Adamson",
    "Barulinho",
    "Bat For Lashes",
    "Bayside",
    "Bazzi",
    "Beach House",
    "Beacon",
    "Beau Projet",
    "Beirut",
    "Benjamin Martins",
    "Biba Dupont",
    "Big Thief",
    "Bill Withers",
    "Billie Eilish",
    "Billie Marten",
    "Billy Talent",
    "Bilo 503",
    "Bingo Players",
    "Birdy",
    "Blasterjaxx",
    "Blonde Redhead",
    "Blouse",
    "Bob Seger",
    "Bodywash",
    "Bombay Bicycle Club",
    "Bon Iver",
    "Boysetsfire",
    "Bram de Looze",
    "Brand New",
    "Breaking Benjamin",
    "Bruno Major",
    "Bullet For My Valentine",
    "Burden Brothers",
    "Burgundy Skies",
    "Bush",
    "CHIC",
    "Calum Scott",
    "CamelPhat",
    "Camila Cabello",
    "Camo Columbo",
    "Cecelya",
    "Cedric Gervais",
    "Charles Bolt",
    "Chocolate Puma",
    "Chris Malinchak",
    "Chumbawamba",
    "Cigarettes After Sex",
    "City of the Sun",
    "Clinton Kane",
    "Clouseau",
    "Cocteau Twins",
    "Coheed and Cambria",
    "Coldplay",
    "Collective Soul",
    "Comet Blue",
    "Cooper Sams",
    "Cora Zea",
    "Counting Crows",
    "Cranes",
    "Crazy Town",
    "Creedence Clearwater Revival",
    "Crumb",
    "Cult Solo",
    "Dada Life",
    "Daft Punk",
    "Damien Rice",
    "Daniel Blumberg",
    "Daryl Hall & John Oates",
    "Daughter",
    "Dave Pad",
    "Dave202",
    "DeLange",
    "Dean Valio",
    "Death Cab for Cutie",
    "Deee-Lite",
    "Deftones",
    "Depeche Mode",
    "Dexys Midnight Runners",
    "Dhyana Thomas",
    "Dillon",
    "Dimitri Vangelis & Wyman",
    "Disturbed",
    "Doeke",
    "Domaine Blanc",
    "Dreyma",
    "Dries Beheydt",
    "DubVision",
    "Dust Follows",
    "EDX",
    "EERA",
    "Eartheater",
    "Ed Sheeran",
    "Efterklang",
    "Electric Light Orchestra",
    "Elementaries",
    "Eline Moss",
    "Ella van der Woude",
    "Ellie Rose",
    "Elmau Dunkel",
    "Elton John",
    "Elvis Presley",
    "Emmanuelle Rimbaud",
    "Emmrose",
    "Epi-Soothe",
    "Erik Frank",
    "Erik Reno",
    "Eroded Sky",
    "Estado De Calma",
    "Eucalyptic",
    "Evan Michael Brown",
    "Eve 6",
    "Evin Iris",
    "Ex:Re",
    "FTampa",
    "Faelt",
    "Fatboy Slim",
    "Father John Misty",
    "Faustix",
    "Fedde Le Grand",
    "Fenne Lily",
    "Finger Eleven",
    "Fink",
    "Five Finger Death Punch",
    "Fleet Foxes",
    "Fleetwood Mac",
    "Florejan",
    "Florejan Verschueren",
    "Foals",
    "Foo Fighters",
    "Foster The People",
    "Fuel",
    "Gabriel & Dresden",
    "Galantis",
    "Gareth Emery",
    "Ghost Of Summer",
    "Gnarls Barkley",
    "Goat Girl",
    "Godsmack",
    "Golden Sleep",
    "Gorgon City",
    "Gotye",
    "Gracie Abrams",
    "Grandaddy",
    "Grover Washington, Jr.",
    "Gustavo Santaolalla",
    "HONNE",
    "Halfway Escape",
    "Hans Voller",
    "Harry Styles",
    "Harvest Silence",
    "Hicham Chahidi",
    "Hilary Hahn",
    "Hilder Sky",
    "Hoobastank",
    "Hooverphonic",
    "Hope Sandoval and the Warm Inventions",
    "Hugar",
    "Ian Wong",
    "Iron & Wine",
    "Isaac Elton",
    "Isobel Campbell",
    "JP Saxe",
    "Jaakko Eino Kalevi",
    "Jacco Wynia",
    "Jack Johnson",
    "Jakob Ahlbom",
    "James Bay",
    "James Brown",
    "Jamiroquai",
    "Jef Martens",
    "Jehnny Beth",
    "Jeremy Olander",
    "Jeremy Zucker",
    "Jerkcurb",
    "Jet",
    "Jimmy Eat World",
    "Job Roggeveen",
    "Joe Jackson",
    "Joep Beving",
    "Johann Sebastian Bach",
    "John Legend",
    "John Mayer",
    "Johnning",
    "Johnny Goth",
    "Josh Kramer",
    "Joshua Radin",
    "Josie Mehlin",
    "Julia Holter",
    "Julian",
    "Junodream",
    "Jurrivh",
    "KAAZE",
    "KISS",
    "KSHMR",
    "Kamal.",
    "Kaskade",
    "Kate Teague",
    "Kensington",
    "Kina",
    "King Princess",
    "Kodaline",
    "Korn",
    "Kornum & Karma",
    "LEFT.",
    "La Acacia",
    "Labi Ramaj",
    "Labrinth",
    "Lambert",
    "Lana Del Rey",
    "Le Verne",
    "Lennon Stella",
    "Leo Nocta",
    "Les Manger Tous",
    "Lewis Capaldi",
    "Light of Sun",
    "Lights & Motion",
    "Lily Allen",
    "Limp Bizkit",
    "Linkin Park",
    "Lit",
    "Lolo Zouaï",
    "Lord Huron",
    "Lost Frequencies",
    "Lost Horse Mine",
    "Low",
    "Low Roar",
    "Loyal Lobos",
    "Lucas & Steve",
    "Lucas Delphy",
    "Lucy Rose",
    "LudoWic",
    "Ludwig van Beethoven",
    "Luna",
    "Lundegard",
    "Lupe Fuentes",
    "Lush",
    "Mac DeMarco",
    "Made Of Gold",
    "Major Lazer",
    "Manse",
    "Manuel Ponce",
    "Manuela",
    "Marc Benjamin",
    "Marc Torch",
    "Mark Milan",
    "Marlies du Mosch",
    "Martin Garrix",
    "Martin Gauffin",
    "Martin Thulin",
    "Martèn LeGrand",
    "Marynka",
    "Massive Attack",
    "Mastrovita",
    "Matteo Myderwyk",
    "Matthew Harvey",
    "Max Richter",
    "May",
    "Mazzy Star",
    "Melissa Etheridge",
    "Men Without Hats",
    "Metallica",
    "Michael Orvind",
    "Mike Candys",
    "Mike Posner",
    "Minxz",
    "Monocle Twins",
    "MorMor",
    "Mordkey",
    "Morgan Page",
    "Mumford & Sons",
    "Muse",
    "Muzz",
    "My Chemical Romance",
    "MØ",
    "NERVO",
    "Natalie Taylor",
    "Nena",
    "New Radicals",
    "Nicky Romero",
    "Nico Casal",
    "Night Sounds",
    "Nightlands",
    "Nils Frahm",
    "Nina June",
    "Nina Nesbitt",
    "No Vacation",
    "Noah Vanden Abeele",
    "Norman Greenbaum",
    "Novo Amor",
    "OMC",
    "Oasis",
    "Of Monsters and Men",
    "Olaars & Will Philips",
    "Oliver Heldens",
    "Oliver Ingrosso",
    "Olivia Belli",
    "One Sentence. Supervisor",
    "Other Lives",
    "Otto Knows",
    "OutKast",
    "Pale Saints",
    "Papa Roach",
    "Parazal",
    "Paris Blohm",
    "Passenger",
    "Patrick Hamilton",
    "Paul Simon",
    "Peals",
    "Philip Bailey",
    "Phoebe Bridgers",
    "Pieter Savenberg",
    "Pieter de Graaf",
    "Pink Floyd",
    "Prince",
    "Puddle Of Mudd",
    "Queen",
    "Queens of the Stone Age",
    "Quintino",
    "R.E.M.",
    "ROSALÍA",
    "RY X",
    "Radical Face",
    "Radiohead",
    "Rage Against The Machine",
    "Rand Aldo",
    "Random Forest",
    "Red Hot Chili Peppers",
    "Regina Spektor",
    "Reina del Mar",
    "Reinhard Vanbergen",
    "Remy Van Kesteren",
    "Rhys Lewis",
    "Rise Against",
    "Rob Zombie",
    "Robbie Rivera",
    "Robert Palmer",
    "Ron Adelaar",
    "Ron Verboom",
    "Rosie Carney",
    "Rouge Haven",
    "Rustin Man",
    "SOAK",
    "Saliva",
    "Sandro Silva",
    "Sarah Davachi",
    "Sasha Sloan",
    "Scary Kids Scaring Kids",
    "Seafret",
    "Search For Atlantis",
    "Sebastián Escofet",
    "Seether",
    "Seth Hills",
    "Sevendust",
    "Shannon Lay",
    "Sharon Van Etten",
    "Shoffy",
    "Sia",
    "Sick Individuals",
    "Silo Silo",
    "Simian",
    "Simple Minds",
    "Sir Roy",
    "Skytech",
    "Slipknot",
    "Slowdive",
    "Smile Empty Soul",
    "Sniff 'n' The Tears",
    "So Vea",
    "Soccer Mommy",
    "Sofiane Pamart",
    "Sofie Tukker",
    "Song Sung",
    "Sorry",
    "Spin Doctors",
    "Spiritualized",
    "St Woods",
    "Stacy Crowne",
    "Staind",
    "Star Slide",
    "Steff da Campo",
    "Steve Aoki",
    "Steve Brian",
    "Steve Gunn",
    "Steve Miller Band",
    "Steven Vrancken",
    "Stevie Nicks",
    "Stevie Wonder",
    "Still Corners",
    "Stone Temple Pilots",
    "Story Of The Year",
    "Sublime",
    "Sufjan Stevens",
    "Sulfur Springs",
    "Sum 41",
    "Swanky Tunes",
    "Sylvain Chauveau",
    "System Of A Down",
    "TOTO",
    "TT",
    "Taking Back Sunday",
    "Taproot",
    "Tash Sultana",
    "Tate McRae",
    "Teodor Wolgers",
    "Terence Trent D'Arby",
    "The 1975",
    "The Beach Boys",
    "The Beatles",
    "The Buggles",
    "The Cardigans",
    "The Cinematic Orchestra",
    "The Clash",
    "The Cure",
    "The Doobie Brothers",
    "The Exies",
    "The Him",
    "The Killers",
    "The Kinks",
    "The Knack",
    "The Lumineers",
    "The Mamas & The Papas",
    "The National",
    "The Offspring",
    "The Osmonds",
    "The Police",
    "The Raconteurs",
    "The Rolling Stones",
    "The Romantics",
    "The Six Parts Seven",
    "The Soft Cavalry",
    "The Tides",
    "The Turtles",
    "The Used",
    "The War On Drugs",
    "The White Stripes",
    "Thin Lizzy",
    "Third Eye Blind",
    "Third Party",
    "Thirty Seconds To Mars",
    "This Mortal Coil",
    "Thom Yorke",
    "Thomas Gold",
    "Thomas Jackson",
    "Threading Hair",
    "Thrice",
    "Tindersticks",
    "Tiz McNamara",
    "Tiësto",
    "Tobtok",
    "Toledo Rains",
    "Tom Kalani",
    "Tom Misch",
    "Tom Odell",
    "Ton Snijders",
    "Trapt",
    "Underoath",
    "Valentin",
    "Van Stiles",
    "Various Artists",
    "Vicetone",
    "Vochey",
    "War",
    "Warpaint",
    "Weezer",
    "Weyes Blood",
    "Wheatus",
    "Whitney",
    "William Duhamel",
    "Wilson Trouvé",
    "Wolf Alice",
    "X-Ecutioners",
    "Yonder Dale",
    "YuMe",
    "Yves V",
    "Zoe Connelly",
    "a-ha",
    "blink-182",
    "cloudcrush",
    "dEUS",
    "k?d",
    "praam",
]

export default artists;